@echo off
FOR /F "tokens=2 skip=4" %%G IN ('svn info --revision HEAD') DO ^
IF NOT DEFINED REVISION SET REVISION=%%G
rem set /a REVISION=%REVISION% + 1
echo // Autogenerated: run updatebuildnr.bat/sh to update > RadegastBuild.cs
echo namespace Radegast >> RadegastBuild.cs
echo { >> RadegastBuild.cs
echo     public static class RadegastBuild { public static int CurrentRev = %REVISION%; } >> RadegastBuild.cs
echo } >> RadegastBuild.cs
