//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radegast.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radegast.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap add_16 {
            get {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap applications_16 {
            get {
                object obj = ResourceManager.GetObject("applications_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap applications_32 {
            get {
                object obj = ResourceManager.GetObject("applications_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap arrow_forward_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_forward_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap arrow_up_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_up_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap computer_16 {
            get {
                object obj = ResourceManager.GetObject("computer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap copy_16 {
            get {
                object obj = ResourceManager.GetObject("copy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cut_16 {
            get {
                object obj = ResourceManager.GetObject("cut_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap documents_16 {
            get {
                object obj = ResourceManager.GetObject("documents_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap documents_32 {
            get {
                object obj = ResourceManager.GetObject("documents_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder_closed_16 {
            get {
                object obj = ResourceManager.GetObject("folder_closed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder_open_16 {
            get {
                object obj = ResourceManager.GetObject("folder_open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GreenOrb_16 {
            get {
                object obj = ResourceManager.GetObject("GreenOrb_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GreenOrbFaded_16 {
            get {
                object obj = ResourceManager.GetObject("GreenOrbFaded_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GridClient {
            get {
                object obj = ResourceManager.GetObject("GridClient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_animation {
            get {
                object obj = ResourceManager.GetObject("inv_folder_animation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_bodypart {
            get {
                object obj = ResourceManager.GetObject("inv_folder_bodypart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_callingcard {
            get {
                object obj = ResourceManager.GetObject("inv_folder_callingcard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_clothing {
            get {
                object obj = ResourceManager.GetObject("inv_folder_clothing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_gesture {
            get {
                object obj = ResourceManager.GetObject("inv_folder_gesture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_landmark {
            get {
                object obj = ResourceManager.GetObject("inv_folder_landmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_lostandfound {
            get {
                object obj = ResourceManager.GetObject("inv_folder_lostandfound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_notecard {
            get {
                object obj = ResourceManager.GetObject("inv_folder_notecard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_object {
            get {
                object obj = ResourceManager.GetObject("inv_folder_object", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_plain_closed {
            get {
                object obj = ResourceManager.GetObject("inv_folder_plain_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_plain_open {
            get {
                object obj = ResourceManager.GetObject("inv_folder_plain_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_script {
            get {
                object obj = ResourceManager.GetObject("inv_folder_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_snapshot {
            get {
                object obj = ResourceManager.GetObject("inv_folder_snapshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_sound {
            get {
                object obj = ResourceManager.GetObject("inv_folder_sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_texture {
            get {
                object obj = ResourceManager.GetObject("inv_folder_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_folder_trash {
            get {
                object obj = ResourceManager.GetObject("inv_folder_trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_animation {
            get {
                object obj = ResourceManager.GetObject("inv_item_animation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_attach {
            get {
                object obj = ResourceManager.GetObject("inv_item_attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_callingcard_offline {
            get {
                object obj = ResourceManager.GetObject("inv_item_callingcard_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_callingcard_online {
            get {
                object obj = ResourceManager.GetObject("inv_item_callingcard_online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_clothing {
            get {
                object obj = ResourceManager.GetObject("inv_item_clothing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_eyes {
            get {
                object obj = ResourceManager.GetObject("inv_item_eyes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_gesture {
            get {
                object obj = ResourceManager.GetObject("inv_item_gesture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_gloves {
            get {
                object obj = ResourceManager.GetObject("inv_item_gloves", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_hair {
            get {
                object obj = ResourceManager.GetObject("inv_item_hair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_jacket {
            get {
                object obj = ResourceManager.GetObject("inv_item_jacket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_landmark {
            get {
                object obj = ResourceManager.GetObject("inv_item_landmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_landmark_visited {
            get {
                object obj = ResourceManager.GetObject("inv_item_landmark_visited", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_notecard {
            get {
                object obj = ResourceManager.GetObject("inv_item_notecard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_object {
            get {
                object obj = ResourceManager.GetObject("inv_item_object", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_object_multi {
            get {
                object obj = ResourceManager.GetObject("inv_item_object_multi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_pants {
            get {
                object obj = ResourceManager.GetObject("inv_item_pants", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_script {
            get {
                object obj = ResourceManager.GetObject("inv_item_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_script_dangerous {
            get {
                object obj = ResourceManager.GetObject("inv_item_script_dangerous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_shape {
            get {
                object obj = ResourceManager.GetObject("inv_item_shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_shirt {
            get {
                object obj = ResourceManager.GetObject("inv_item_shirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_shoes {
            get {
                object obj = ResourceManager.GetObject("inv_item_shoes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_skin {
            get {
                object obj = ResourceManager.GetObject("inv_item_skin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_skirt {
            get {
                object obj = ResourceManager.GetObject("inv_item_skirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_snapshot {
            get {
                object obj = ResourceManager.GetObject("inv_item_snapshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_socks {
            get {
                object obj = ResourceManager.GetObject("inv_item_socks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_sound {
            get {
                object obj = ResourceManager.GetObject("inv_item_sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_texture {
            get {
                object obj = ResourceManager.GetObject("inv_item_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_underpants {
            get {
                object obj = ResourceManager.GetObject("inv_item_underpants", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap inv_item_undershirt {
            get {
                object obj = ResourceManager.GetObject("inv_item_undershirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lsl_scripts_16 {
            get {
                object obj = ResourceManager.GetObject("lsl_scripts_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap paste_16 {
            get {
                object obj = ResourceManager.GetObject("paste_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radegast.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radegast 1.3.
        /// </summary>
        public static string RadegastTitle {
            get {
                return ResourceManager.GetString("RadegastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Czukor.
        /// </summary>
        public static string SleekAuthor {
            get {
                return ResourceManager.GetString("SleekAuthor", resourceCulture);
            }
        }
    }
}
